! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Wed Mar 25 16:15:23 2020
! Working directory    : /net/fs11/d0/jamiekel/GEOS_Chem_v11-01/GC_PYR_Nitro_6/KPP/Custom
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'MONX           ','NNAP           ','SO4            ', & ! index 1 - 3
     'MSA            ','LISOPOH        ','LISOPNO3       ', & ! index 4 - 6
     'LBRO2H         ','LBRO2N         ','LTRO2H         ', & ! index 7 - 9
     'LTRO2N         ','LXRO2H         ','LXRO2N         ', & ! index 10 - 12
     'PYAC           ','CO2            ','RX1            ', & ! index 13 - 15
     'RX2            ','RX3            ','RX4            ', & ! index 16 - 18
     'RX5            ','RX6            ','RX7            ', & ! index 19 - 21
     'RX8            ','RX9            ','RX10           ', & ! index 22 - 24
     'RX11           ','RX12           ','RX13           ', & ! index 25 - 27
     'RX14           ','RX15           ','RX16           ', & ! index 28 - 30
     'RX17           ','RX18           ','RX19           ', & ! index 31 - 33
     'RX20           ','RX21           ','RX22           ', & ! index 34 - 36
     'RX23           ','RX24           ','RX25           ', & ! index 37 - 39
     'RX26           ','RX27           ','RX28           ', & ! index 40 - 42
     'RX29           ','RX30           ','RX31           ', & ! index 43 - 45
     'RX32           ','RX33           ','RX34           ', & ! index 46 - 48
     'RX35           ','RX36           ','RX37           ', & ! index 49 - 51
     'RX38           ','RX39           ','RX40           ', & ! index 52 - 54
     'RX41           ','RX42           ','RX43           ', & ! index 55 - 57
     'RX44           ','RX45           ','RX46           ', & ! index 58 - 60
     'RX47           ','RX48           ','RX49           ', & ! index 61 - 63
     'RX50           ','RX51           ','RX52           ', & ! index 64 - 66
     'RX53           ','RX54           ','RX55           ', & ! index 67 - 69
     'RX56           ','RX57           ','RX58           ', & ! index 70 - 72
     'RX59           ','RX60           ','RX61           ', & ! index 73 - 75
     'RX62           ','RX63           ','RX64           ', & ! index 76 - 78
     'RX65           ','RX66           ','RX67           ', & ! index 79 - 81
     'RX68           ','RX69           ','RX70           ', & ! index 82 - 84
     'RX71           ','RX72           ','RX73           ', & ! index 85 - 87
     'RX74           ','RX75           ','RX76           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'RX77           ','RX78           ','RX79           ', & ! index 91 - 93
     'RX80           ','RX81           ','RX82           ', & ! index 94 - 96
     'RX83           ','RX84           ','RX85           ', & ! index 97 - 99
     'RX86           ','RX87           ','RX88           ', & ! index 100 - 102
     'RX89           ','RX90           ','RX91           ', & ! index 103 - 105
     'RX92           ','RX93           ','RX94           ', & ! index 106 - 108
     'RX95           ','RX96           ','RX97           ', & ! index 109 - 111
     'RX98           ','RX99           ','RX100          ', & ! index 112 - 114
     'RX101          ','RX102          ','RX103          ', & ! index 115 - 117
     'RX104          ','RX105          ','RX106          ', & ! index 118 - 120
     'RX107          ','RX108          ','RX109          ', & ! index 121 - 123
     'RX110          ','RX111          ','RX112          ', & ! index 124 - 126
     'RX113          ','RX114          ','RX115          ', & ! index 127 - 129
     'PRX1           ','ACE            ','PRX2           ', & ! index 130 - 132
     'ACY            ','PRX3           ','ANT            ', & ! index 133 - 135
     'PRX4           ','BAA            ','PRX5           ', & ! index 136 - 138
     'BAP            ','PRX6           ','BBF            ', & ! index 139 - 141
     'PRX7           ','BHP            ','PRX8           ', & ! index 142 - 144
     'BKF            ','PRX9           ','CHR            ', & ! index 145 - 147
     'PRX10          ','DAHA           ','PRX11          ', & ! index 148 - 150
     'FLA            ','PRX12          ','FLO            ', & ! index 151 - 153
     'PRX13          ','ICDP           ','PRX14          ', & ! index 154 - 156
     'PRX15          ','PRX16          ','PRX17          ', & ! index 157 - 159
     'PHE            ','PRX18          ','PRX19          ', & ! index 160 - 162
     'PRX20          ','PRX21          ','PRX22          ', & ! index 163 - 165
     'PRX23          ','PRX24          ','PRX25          ', & ! index 166 - 168
     'PRX26          ','PRX27          ','PRX28          ', & ! index 169 - 171
     'PRX29          ','PRX30          ','PRX31          ', & ! index 172 - 174
     'PRX32          ','PRX33          ','PRX34          ', & ! index 175 - 177
     'PRX35          ','PRX36          ','PRX37          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_2 = (/ &
     'PRX38          ','PRX39          ','PRX40          ', & ! index 181 - 183
     'PRX41          ','PRX42          ','PRX43          ', & ! index 184 - 186
     'PRX44          ','PRX45          ','PRX46          ', & ! index 187 - 189
     'PRX47          ','PRX48          ','PRX49          ', & ! index 190 - 192
     'PRX50          ','PRX51          ','PRX52          ', & ! index 193 - 195
     'PRX53          ','PRX54          ','PRX55          ', & ! index 196 - 198
     'PRX56          ','PRX57          ','PRX58          ', & ! index 199 - 201
     'PRX59          ','PRX60          ','PRX61          ', & ! index 202 - 204
     'PRX62          ','PRX63          ','PRX64          ', & ! index 205 - 207
     'PRX65          ','PRX66          ','PRX67          ', & ! index 208 - 210
     'PRX68          ','PRX69          ','PRX70          ', & ! index 211 - 213
     'PRX71          ','PRX72          ','PRX73          ', & ! index 214 - 216
     'PRX74          ','PRX75          ','PRX76          ', & ! index 217 - 219
     'PRX77          ','PRX78          ','PRX79          ', & ! index 220 - 222
     'PRX80          ','PRX81          ','PRX82          ', & ! index 223 - 225
     'PRX83          ','PRX84          ','PRX85          ', & ! index 226 - 228
     'PRX86          ','PRX87          ','PRX88          ', & ! index 229 - 231
     'PRX89          ','PRX90          ','PRX91          ', & ! index 232 - 234
     'PRX92          ','PRX93          ','PRX94          ', & ! index 235 - 237
     'PRX95          ','PRX96          ','PRX97          ', & ! index 238 - 240
     'PRX98          ','PRX99          ','PRX100         ', & ! index 241 - 243
     'PRX101         ','PRX102         ','PRX103         ', & ! index 244 - 246
     'PRX104         ','PRX105         ','PRX106         ', & ! index 247 - 249
     'PRX107         ','PRX108         ','PRX109         ', & ! index 250 - 252
     'PRX110         ','PRX111         ','PRX112         ', & ! index 253 - 255
     'PRX113         ','PRX114         ','PRX115         ', & ! index 256 - 258
     'TOLU           ','XYLE           ','CHBr3          ', & ! index 259 - 261
     'CH2Br2         ','CH3Br          ','ANTOCPI        ', & ! index 262 - 264
     'ACEBCPO        ','ACEBCPI        ','ACEOCPO        ', & ! index 265 - 267
     'ACEOCPI        ','ANTBCPI        ','ACYBCPO        ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_3 = (/ &
     'ACYBCPI        ','ACYOCPO        ','ACYOCPI        ', & ! index 271 - 273
     'ANTBCPO        ','ANTOCPO        ','BAABCPO        ', & ! index 274 - 276
     'BAABCPI        ','BAAOCPI        ','BAPBCPO        ', & ! index 277 - 279
     'BAPOCPO        ','BAAOCPO        ','BBFBCPI        ', & ! index 280 - 282
     'BBFOCPI        ','BHPBCPO        ','BHPOCPO        ', & ! index 283 - 285
     'BAPOCPI        ','BKFBCPO        ','BKFBCPI        ', & ! index 286 - 288
     'BKFOCPO        ','BBFBCPO        ','CHRBCPO        ', & ! index 289 - 291
     'CHRBCPI        ','CHROCPO        ','CHROCPI        ', & ! index 292 - 294
     'BBFOCPO        ','DAHABCPO       ','DAHABCPI       ', & ! index 295 - 297
     'DAHAOCPO       ','DAHAOCPI       ','BAPBCPI        ', & ! index 298 - 300
     'FLABCPO        ','FLABCPI        ','FLAOCPO        ', & ! index 301 - 303
     'FLAOCPI        ','BHPBCPI        ','FLOBCPO        ', & ! index 304 - 306
     'FLOBCPI        ','FLOOCPO        ','FLOOCPI        ', & ! index 307 - 309
     'BHPOCPI        ','ICDPBCPO       ','ICDPBCPI       ', & ! index 310 - 312
     'ICDPOCPO       ','ICDPOCPI       ','NAP            ', & ! index 313 - 315
     'NAPAD          ','BKFOCPI        ','PHEBCPO        ', & ! index 316 - 318
     'PHEBCPI        ','PHEOCPO        ','PHEOCPI        ', & ! index 319 - 321
     'BENZ           ','PPN            ','BrNO2          ', & ! index 322 - 324
     'IEPOX          ','PMNN           ','BRO2           ', & ! index 325 - 327
     'TRO2           ','XRO2           ','N2O5           ', & ! index 328 - 330
     'PAN            ','ALK4           ','HNO2           ', & ! index 331 - 333
     'MAP            ','MPN            ','RA3P           ', & ! index 334 - 336
     'RB3P           ','DMS            ','C3H8           ', & ! index 337 - 339
     'ETP            ','HNO4           ','MP             ', & ! index 340 - 342
     'HOBr           ','Br2            ','HBr            ', & ! index 343 - 345
     'MAOP           ','RP             ','PYRBCPO        ', & ! index 346 - 348
     'PYRBCPI        ','PYROCPO        ','PYROCPI        ', & ! index 349 - 351
     'BrNO3          ','PP             ','PRPN           ', & ! index 352 - 354
     'ETHLN          ','PYRAD          ','BAPBAD         ', & ! index 355 - 357
     'C2H6           ','H2O2           ','ATOOH          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_4 = (/ &
     'R4P            ','HCOOH          ','PYR            ', & ! index 361 - 363
     'VRP            ','BAPC           ','RIP            ', & ! index 364 - 366
     'IAP            ','MRP            ','DHMOB          ', & ! index 367 - 369
     'MOBA           ','BAPCBCPI       ','BAPCBCPO       ', & ! index 370 - 372
     'BAPB           ','BAPBBCPI       ','BAPCOCPI       ', & ! index 373 - 375
     'BAPBBCPO       ','BAPCOCPO       ','BAPBOCPI       ', & ! index 376 - 378
     'BAPBOCPO       ','INPN           ','ISNP           ', & ! index 379 - 381
     'ISOPNB         ','IEPOXOO        ','MOBAOO         ', & ! index 382 - 384
     'ROH            ','DIBOO          ','MACRNO2        ', & ! index 385 - 387
     'PMN            ','MVKOO          ','ACTA           ', & ! index 388 - 390
     'ACET           ','CH3CHOO        ','GAOO           ', & ! index 391 - 393
     'ISNOHOO        ','MGLYOO         ','CH2OO          ', & ! index 394 - 396
     'ISOP           ','PRPE           ','BrO            ', & ! index 397 - 399
     'MVKN           ','PROPNN         ','MGLOO          ', & ! index 400 - 402
     'ISNOOB         ','HNO3           ','A3O2           ', & ! index 403 - 405
     'GLYX           ','MAOPO2         ','ISOPND         ', & ! index 406 - 408
     'MACROO         ','MACRN          ','PO2            ', & ! index 409 - 411
     'ISNOOA         ','MAN2           ','PRN1           ', & ! index 412 - 414
     'B3O2           ','KO2            ','GLYC           ', & ! index 415 - 417
     'HC5OO          ','ETO2           ','VRO2           ', & ! index 418 - 420
     'RCO3           ','R4N1           ','ATO2           ', & ! index 421 - 423
     'ISN1           ','MAO3           ','SO2            ', & ! index 424 - 426
     'MGLY           ','INO2           ','RIO2           ', & ! index 427 - 429
     'HC5            ','CH2O           ','MRO2           ', & ! index 430 - 432
     'ISOPNBO2       ','ISOPNDO2       ','HAC            ', & ! index 433 - 435
     'R4O2           ','ALD2           ','R4N2           ', & ! index 436 - 438
     'MACR           ','MVK            ','MEK            ', & ! index 439 - 441
     'MCO3           ','OH             ','O3             ', & ! index 442 - 444
     'MO2            ','CO             ','RCHO           ', & ! index 445 - 447
     'NO3            ','HO2            ','NO2            ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(9) :: SPC_NAMES_5 = (/ &
     'Br             ','NO             ','CH4            ', & ! index 451 - 453
     'EOH            ','H2             ','H2O            ', & ! index 454 - 456
     'MOH            ','O2             ','RCOOH          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(459) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2, SPC_NAMES_3, SPC_NAMES_4, &
    SPC_NAMES_5 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '         O3 + NO --> NO2 + O2                                                                       ', & ! index 1
     '         OH + O3 --> HO2 + O2                                                                       ', & ! index 2
     '        O3 + HO2 --> OH + 2 O2                                                                      ', & ! index 3
     '        O3 + NO2 --> NO3 + O2                                                                       ', & ! index 4
     '        O3 + MO2 --> CH2O + HO2 + 2 O2                                                              ', & ! index 5
     '            2 OH --> O3 + H2O                                                                       ', & ! index 6
     '            2 OH --> H2O2                                                                           ', & ! index 7
     '        OH + HO2 --> H2O + O2                                                                       ', & ! index 8
     '       H2O2 + OH --> HO2 + H2O                                                                      ', & ! index 9
     '        HO2 + NO --> OH + NO2                                                                       ', & ! index 10
     '           2 HO2 --> H2O2                                                                           ', & ! index 11
     '         OH + H2 --> HO2 + H2O                                                                      ', & ! index 12
     '         OH + CO --> CO2 + HO2                                                                      ', & ! index 13
     '        OH + CH4 --> MO2 + H2O                                                                      ', & ! index 14
     '        MO2 + NO --> CH2O + HO2 + NO2                                                               ', & ! index 15
     '       MO2 + HO2 --> MP + O2                                                                        ', & ! index 16
     '           2 MO2 --> CH2O + MOH + O2                                                                ', & ! index 17
     '           2 MO2 --> 2 CH2O + 2 HO2                                                                 ', & ! index 18
     '         MP + OH --> MO2 + H2O                                                                      ', & ! index 19
     '         MP + OH --> CH2O + OH + H2O                                                                ', & ! index 20
     '      ATOOH + OH --> ATO2 + H2O                                                                     ', & ! index 21
     '      ATOOH + OH --> MGLY + OH + H2O                                                                ', & ! index 22
     '       CH2O + OH --> CO + HO2 + H2O                                                                 ', & ! index 23
     '        OH + NO2 --> HNO3                                                                           ', & ! index 24
     '       HNO3 + OH --> NO3 + H2O                                                                      ', & ! index 25
     '         OH + NO --> HNO2                                                                           ', & ! index 26
     '       HNO2 + OH --> NO2 + H2O                                                                      ', & ! index 27
     '       HO2 + NO2 --> HNO4                                                                           ', & ! index 28
     '            HNO4 --> HO2 + NO2                                                                      ', & ! index 29
     '       HNO4 + OH --> NO2 + H2O + O2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '       NO3 + HO2 --> OH + NO2 + O2                                                                  ', & ! index 31
     '        NO3 + NO --> 2 NO2                                                                          ', & ! index 32
     '        OH + NO3 --> HO2 + NO2                                                                      ', & ! index 33
     '       NO3 + NO2 --> N2O5                                                                           ', & ! index 34
     '            N2O5 --> NO3 + NO2                                                                      ', & ! index 35
     '      HCOOH + OH --> CO2 + HO2 + H2O                                                                ', & ! index 36
     '        OH + MOH --> CH2O + HO2                                                                     ', & ! index 37
     '       NO3 + NO2 --> NO2 + NO + O2                                                                  ', & ! index 38
     '      CH2O + NO3 --> HNO3 + CO + HO2                                                                ', & ! index 39
     '       ALD2 + OH --> 0.05 CH2O + 0.95 MCO3 + 0.05 CO + 0.05 HO2                                     ', & ! index 40
     '      ALD2 + NO3 --> HNO3 + MCO3                                                                    ', & ! index 41
     '      MCO3 + NO2 --> PAN                                                                            ', & ! index 42
     '             PAN --> MCO3 + NO2                                                                     ', & ! index 43
     '       MCO3 + NO --> CO2 + MO2 + NO2                                                                ', & ! index 44
     '       C2H6 + OH --> ETO2 + H2O                                                                     ', & ! index 45
     '       ETO2 + NO --> ALD2 + HO2 + NO2                                                               ', & ! index 46
     '       C3H8 + OH --> B3O2                                                                           ', & ! index 47
     '       C3H8 + OH --> A3O2                                                                           ', & ! index 48
     '       A3O2 + NO --> RCHO + HO2 + NO2                                                               ', & ! index 49
     '        PO2 + NO --> CH2O + ALD2 + HO2 + NO2                                                        ', & ! index 50
     '       ALK4 + OH --> R4O2                                                                           ', & ! index 51
     '       R4O2 + NO --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 + 0.19 MEK + 0.18 MO2', & ! index 52
     '       R4O2 + NO --> R4N2                                                                           ', & ! index 53
     '       R4N1 + NO --> 0.39 CH2O + 0.3 R4O2 + 0.75 ALD2 + 0.57 RCHO + 2 NO2                           ', & ! index 54
     '       ATO2 + NO --> 0.96 CH2O + 0.04 R4N2 + 0.96 MCO3 + 0.96 NO2                                   ', & ! index 55
     '        KO2 + NO --> 0.93 ALD2 + 0.07 R4N2 + 0.93 MCO3 + 0.93 NO2                                   ', & ! index 56
     '       RIO2 + NO --> 0.047 ISOPNB + 0.1 DIBOO + 0.07 ISOPND + 0.123 HC5 + 0.66 CH2O + 0.26 MACR + 0.', & ! index 57
     '            RIO2 --> 0.5 GLYX + 0.5 GLYC + 0.5 MGLY + CH2O + 0.5 HAC + OH + 2 HO2                   ', & ! index 58
     '       VRO2 + NO --> 0.12 MVKN + 0.53 GLYC + 0.35 MGLY + 0.35 CH2O + 0.53 MCO3 + 0.35 HO2 + 0.88 NO2', & ! index 59
     '       MRO2 + NO --> 0.15 MACRN + 0.122 MGLY + 0.122 CH2O + 0.728 HAC + 0.728 CO + 0.85 HO2 + 0.85 N' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '            MRO2 --> HAC + OH + CO                                                                  ', & ! index 61
     '       MAN2 + NO --> 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 OH + 0.5 CO + 1.5 NO2                   ', & ! index 62
     '       B3O2 + NO --> ACET + HO2 + NO2                                                               ', & ! index 63
     '       INO2 + NO --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK + 0.8 HO2 + 1.3 NO2   ', & ! index 64
     '      INO2 + NO3 --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK + 0.8 HO2 + 1.3 NO2   ', & ! index 65
     '      ISN1 + NO3 --> 0.4 ISNOOB + 0.6 HNO3 + 0.6 ISNOOA                                             ', & ! index 66
     '    ISNOOA + NO3 --> R4N2 + CO + HO2 + NO2                                                          ', & ! index 67
     '     ISNOOA + NO --> R4N2 + CO + HO2 + NO2                                                          ', & ! index 68
     '    ISNOOA + NO2 --> PMN                                                                            ', & ! index 69
     '    ISNOOA + HO2 --> 0.75 RP + 0.25 O3 + 0.25 RCOOH                                                 ', & ! index 70
     '    ISNOOB + NO3 --> GLYX + R4N2 + 2 NO2                                                            ', & ! index 71
     '     ISNOOB + NO --> 0.94 GLYX + 0.94 R4N2 + 1.88 NO2                                               ', & ! index 72
     '    ISNOOB + HO2 --> INPN                                                                           ', & ! index 73
     '    ISNOOB + MO2 --> 0.7 GLYX + 0.75 CH2O + 0.7 R4N2 + 0.5 HO2 + 0.7 NO2 + 0.25 MOH                 ', & ! index 74
     '       ISN1 + O3 --> 0.7 GLYX + 0.75 CH2O + 0.3 R4N2 + 0.5 HO2 + 0.7 NO2 + 0.25 MOH                 ', & ! index 75
     '       ISN1 + OH --> 0.655 ISNOHOO + 0.345 ISNOOA                                                   ', & ! index 76
     '    ISNOHOO + NO --> 0.919 GLYX + 0.934 R4N2 + 0.934 HO2                                            ', & ! index 77
     '   ISNOHOO + HO2 --> INPN                                                                           ', & ! index 78
     '   ISNOHOO + MO2 --> 0.7 GLYX + 0.75 CH2O + 0.7 R4N2 + 1.2 HO2 + 0.25 MOH                           ', & ! index 79
     '          2 INO2 --> 0.5 ISOPND + 1.2 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK + 0.8 HO2', & ! index 80
     '       PRN1 + NO --> CH2O + ALD2 + 2 NO2                                                            ', & ! index 81
     '      ALK4 + NO3 --> HNO3 + R4O2                                                                    ', & ! index 82
     '       R4N2 + OH --> R4N1 + H2O                                                                     ', & ! index 83
     '       ACTA + OH --> CO2 + MO2 + H2O                                                                ', & ! index 84
     '       OH + RCHO --> RCO3 + H2O                                                                     ', & ! index 85
     '      RCO3 + NO2 --> PPN                                                                            ', & ! index 86
     '             PPN --> RCO3 + NO2                                                                     ', & ! index 87
     '      MAO3 + NO2 --> PMN                                                                            ', & ! index 88
     '             PMN --> MAO3 + NO2                                                                     ', & ! index 89
     '       RCO3 + NO --> ETO2 + NO2                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '       MAO3 + NO --> CO2 + 0.5 CH2O + 0.5 MCO3 + 0.5 MO2 + 0.5 CO + NO2                             ', & ! index 91
     '      RCHO + NO3 --> HNO3 + RCO3                                                                    ', & ! index 92
     '       ACET + OH --> ATO2 + H2O                                                                     ', & ! index 93
     '      A3O2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.75 RCHO + HO2 + 0.25 MOH                              ', & ! index 94
     '       PO2 + MO2 --> 0.25 ROH + 1.25 CH2O + 0.16 HAC + 0.5 ALD2 + 0.09 RCHO + HO2 + 0.25 MOH        ', & ! index 95
     '      R4O2 + HO2 --> R4P                                                                            ', & ! index 96
     '      R4N1 + HO2 --> R4N2                                                                           ', & ! index 97
     '      ATO2 + HO2 --> 0.85 ATOOH + 0.15 CH2O + 0.15 MCO3 + 0.15 OH                                   ', & ! index 98
     '       KO2 + HO2 --> 0.85 ATOOH + 0.15 ALD2 + 0.15 MCO3 + 0.15 OH                                   ', & ! index 99
     '      RIO2 + HO2 --> 0.88 RIP + 0.12 CH2O + 0.047 MACR + 0.073 MVK + 0.12 OH + 0.12 HO2             ', & ! index 100
     '      VRO2 + HO2 --> 0.1 VRP + 0.578 GLYC + 0.102 MGLY + 0.102 CH2O + 0.187 MEK + 0.578 MCO3 + 0.68 ', & ! index 101
     '      MRO2 + HO2 --> MRP                                                                            ', & ! index 102
     '      MAN2 + HO2 --> 0.85 ISNP + 0.075 PROPNN + 0.075 MGLY + 0.075 CH2O + 0.15 OH + 0.075 CO + 0.075', & ! index 103
     '      B3O2 + HO2 --> RB3P                                                                           ', & ! index 104
     '      INO2 + HO2 --> INPN                                                                           ', & ! index 105
     '      PRN1 + HO2 --> PRPN                                                                           ', & ! index 106
     '        MEK + OH --> KO2 + H2O                                                                      ', & ! index 107
     '      ETO2 + MO2 --> 0.75 CH2O + 0.75 ALD2 + HO2 + 0.25 EOH + 0.25 MOH                              ', & ! index 108
     '       MEK + NO3 --> HNO3 + KO2                                                                     ', & ! index 109
     '      R4O2 + MO2 --> 0.25 ROH + 0.16 ACET + 0.03 A3O2 + 0.09 B3O2 + 0.16 ETO2 + 0.75 CH2O + 0.16 ALD', & ! index 110
     '      R4N1 + MO2 --> 0.25 ROH + 0.95 CH2O + 0.15 R4O2 + 0.38 ALD2 + 0.54 RCHO + 0.5 HO2 + NO2 + 0.25', & ! index 111
     '      ATO2 + MO2 --> 0.5 MGLY + 0.5 CH2O + 0.2 HAC + 0.3 MCO3 + 0.3 HO2 + 0.5 MOH                   ', & ! index 112
     '       KO2 + MO2 --> 0.25 ROH + 0.75 CH2O + 0.5 ALD2 + 0.25 MEK + 0.5 MCO3 + 0.5 HO2 + 0.25 MOH     ', & ! index 113
     '      RIO2 + MO2 --> 0.24 ROH + 0.3 HC5 + 1.22 CH2O + 0.18 MACR + 0.28 MVK + 1.1 HO2 + 0.24 MOH     ', & ! index 114
     '          2 RIO2 --> 0.48 ROH + 0.5 HC5 + 0.92 CH2O + 0.36 MACR + 0.56 MVK + 1.28 HO2               ', & ! index 115
     '     HC5OO + MO2 --> 0.25 ROH + 0.13 GLYC + 0.29 MGLY + 0.95 CH2O + 0.18 HAC + 0.25 MEK + 0.33 CO + ', & ! index 116
     '      VRO2 + MO2 --> 0.25 ROH + 0.36 GLYC + 0.14 MGLY + 0.89 CH2O + 0.25 MEK + 0.36 MCO3 + 0.64 HO2 ', & ! index 117
     '      MRO2 + MO2 --> 0.15 ROH + 0.255 MGLY + 1.255 CH2O + 0.595 HAC + 0.595 CO + 1.7 HO2            ', & ! index 118
     '      MAN2 + MO2 --> 0.375 PROPNN + 0.375 MGLY + 0.625 CH2O + 0.25 R4N2 + 0.375 CO + 0.375 HO2 + 0.3', & ! index 119
     '      B3O2 + MO2 --> 0.25 ROH + 0.75 ACET + 0.75 CH2O + HO2 + 0.25 MOH                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '      INO2 + MO2 --> 0.25 ISOPND + 0.6 ISN1 + 0.115 HC5 + 0.785 CH2O + 0.018 MACR + 0.018 MVK + 0.9 ', & ! index 121
     '      PRN1 + MO2 --> 0.25 ROH + 1.25 CH2O + 0.5 ALD2 + 0.25 RCHO + 0.5 HO2 + NO2 + 0.25 MOH         ', & ! index 122
     '        OH + EOH --> ALD2 + HO2                                                                     ', & ! index 123
     '        ROH + OH --> RCHO + HO2                                                                     ', & ! index 124
     '          2 ETO2 --> 2 ALD2 + 2 HO2                                                                 ', & ! index 125
     '          2 ETO2 --> ALD2 + EOH                                                                     ', & ! index 126
     '      ETO2 + HO2 --> ETP                                                                            ', & ! index 127
     '      A3O2 + HO2 --> RA3P                                                                           ', & ! index 128
     '       PO2 + HO2 --> PP                                                                             ', & ! index 129
     '      MCO3 + HO2 --> 0.41 MAP + 0.15 ACTA + 0.44 OH + 0.15 O3 + 0.44 MO2                            ', & ! index 130
     '      RCO3 + HO2 --> 0.41 RP + 0.44 ETO2 + 0.44 OH + 0.15 O3 + 0.15 RCOOH                           ', & ! index 131
     '      MAO3 + HO2 --> 0.41 MAOP + 0.59 CH2O + 0.44 OH + 0.15 O3 + 0.39 MO2 + 0.39 CO                 ', & ! index 132
     '       PRPE + OH --> PO2                                                                            ', & ! index 133
     '       PRPE + O3 --> 0.12 CH3CHOO + 0.12 CH2OO + 0.5 CH2O + 0.5 ALD2 + 0.36 OH + 0.28 MO2 + 0.56 CO ', & ! index 134
     '        PMN + OH --> HAC + CO + NO2                                                                 ', & ! index 135
     '        PMN + O3 --> CH2O + MCO3 + NO3                                                              ', & ! index 136
     '       GLYC + OH --> 0.361 CO2 + 0.134 HCOOH + 0.134 GLYX + 0.732 CH2O + 0.227 OH + 0.505 CO + 0.773', & ! index 137
     '       GLYC + OH --> HCOOH + OH + CO                                                                ', & ! index 138
     '      PRPE + NO3 --> PRN1                                                                           ', & ! index 139
     '       GLYX + OH --> 2 CO + HO2                                                                     ', & ! index 140
     '       MGLY + OH --> MCO3 + CO                                                                      ', & ! index 141
     '      GLYX + NO3 --> HNO3 + 2 CO + HO2                                                              ', & ! index 142
     '      MGLY + NO3 --> HNO3 + MCO3 + CO                                                               ', & ! index 143
     '       ISOP + OH --> LISOPOH + RIO2                                                                 ', & ! index 144
     '        MVK + OH --> VRO2                                                                           ', & ! index 145
     '       MACR + OH --> 0.53 MAO3 + 0.47 MRO2                                                          ', & ! index 146
     '        HAC + OH --> MGLY + HO2                                                                     ', & ! index 147
     '        HAC + OH --> 0.5 CO2 + 0.5 HCOOH + 0.5 ACTA + OH + 0.5 MO2 + 0.5 CO                         ', & ! index 148
     '     A3O2 + MCO3 --> MO2 + RCHO + HO2                                                               ', & ! index 149
     '      PO2 + MCO3 --> CH2O + ALD2 + MO2 + HO2                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '     A3O2 + MCO3 --> ACTA + RCHO                                                                    ', & ! index 151
     '      PO2 + MCO3 --> ACTA + 0.65 HAC + 0.35 RCHO                                                    ', & ! index 152
     '       ISOP + O3 --> 0.044 MVKOO + 0.12 CH2OO + 0.128 PRPE + 0.066 MACROO + 0.054 VRO2 + 0.709 CH2O ', & ! index 153
     '        MVK + O3 --> 0.12 CH2OO + 0.12 MGLOO + 0.5 MGLY + 0.6 CH2O + 0.1 ALD2 + 0.28 MCO3 + 0.36 OH ', & ! index 154
     '       MACR + O3 --> 0.022 MGLYOO + 0.211 CH2OO + 0.88 MGLY + 0.12 CH2O + 0.099 MCO3 + 0.415 OH + 0.', & ! index 155
     '      ISOP + NO3 --> LISOPNO3 + INO2                                                                ', & ! index 156
     '      MACR + NO3 --> MAN2                                                                           ', & ! index 157
     '      MACR + NO3 --> HNO3 + MAO3                                                                    ', & ! index 158
     '      RCO3 + MO2 --> ETO2 + CH2O + HO2                                                              ', & ! index 159
     '      MAO3 + MO2 --> 2 CH2O + MCO3 + HO2                                                            ', & ! index 160
     '      RCO3 + MO2 --> CH2O + RCOOH                                                                   ', & ! index 161
     '      MAO3 + MO2 --> CH2O + RCOOH                                                                   ', & ! index 162
     '       INPN + OH --> MEK + OH + NO2                                                                 ', & ! index 163
     '       INPN + OH --> 0.36 INO2 + 0.64 R4N2 + 0.64 OH                                                ', & ! index 164
     '       PRPN + OH --> 0.791 PROPNN + 0.209 PRN1 + 0.791 OH                                           ', & ! index 165
     '        ETP + OH --> 0.36 ETO2 + 0.64 ALD2 + 0.64 OH                                                ', & ! index 166
     '       RA3P + OH --> 0.36 A3O2 + 0.64 OH + 0.64 RCHO                                                ', & ! index 167
     '       RB3P + OH --> 0.791 ACET + 0.209 B3O2 + 0.791 OH                                             ', & ! index 168
     '        R4P + OH --> 0.209 R4O2 + 0.791 OH + 0.791 RCHO                                             ', & ! index 169
     '         RP + OH --> RCO3                                                                           ', & ! index 170
     '         PP + OH --> 0.209 PO2 + 0.791 HAC + 0.791 OH                                               ', & ! index 171
     '        RIP + OH --> 0.387 RIO2 + 0.613 HC5 + 0.613 OH                                              ', & ! index 172
     '        RIP + OH --> IEPOX + OH                                                                     ', & ! index 173
     '      IEPOX + OH --> IEPOXOO                                                                        ', & ! index 174
     '   IEPOXOO + HO2 --> 0.2 CO2 + 0.074 HCOOH + 0.275 GLYX + 0.275 GLYC + 0.275 MGLY + 0.375 CH2O + 0.7', & ! index 175
     '    IEPOXOO + NO --> 0.2 CO2 + 0.074 HCOOH + 0.275 GLYX + 0.275 GLYC + 0.275 MGLY + 0.375 CH2O + 0.7', & ! index 176
     '        IAP + OH --> 0.654 DHMOB + 0.346 HC5OO + 0.654 OH                                           ', & ! index 177
     '        VRP + OH --> 0.209 VRO2 + 0.791 MEK + 0.791 OH                                              ', & ! index 178
     '        MRP + OH --> MRO2                                                                           ', & ! index 179
     '        MRP + OH --> CO2 + HAC + OH                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '       MAOP + OH --> MAO3                                                                           ', & ! index 181
     '       MAOP + OH --> MAOPO2                                                                         ', & ! index 182
     '   MAOPO2 + MCO3 --> 2 CO2 + HAC + OH + MO2                                                         ', & ! index 183
     '   MAOPO2 + MCO3 --> ACTA + MEK                                                                     ', & ! index 184
     '    MAOPO2 + MO2 --> 0.7 CO2 + 0.3 ROH + CH2O + 0.7 HAC + 0.7 OH + 0.7 HO2                          ', & ! index 185
     '        2 MAOPO2 --> 2 CO2 + 2 HAC + 2 OH                                                           ', & ! index 186
     '    MAOPO2 + HO2 --> CO2 + HAC + 2 OH                                                               ', & ! index 187
     '     MAOPO2 + NO --> CO2 + HAC + OH + NO2                                                           ', & ! index 188
     '     MAOPO2 + NO --> HNO3                                                                           ', & ! index 189
     '        MAP + OH --> MCO3                                                                           ', & ! index 190
     '      C2H6 + NO3 --> HNO3 + ETO2                                                                    ', & ! index 191
     '        HC5 + O3 --> 0.055 GAOO + 0.055 MGLYOO + 0.5 GLYC + 0.5 MGLY + 0.445 CH2O + 0.445 MCO3 + 0.8', & ! index 192
     '          2 MCO3 --> 2 MO2                                                                          ', & ! index 193
     '      MCO3 + MO2 --> CH2O + MO2 + HO2                                                               ', & ! index 194
     '      MCO3 + MO2 --> ACTA + CH2O                                                                    ', & ! index 195
     '     R4O2 + MCO3 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 + 0.19 MEK + MO2 + 0.', & ! index 196
     '     ATO2 + MCO3 --> CH2O + MCO3 + MO2                                                              ', & ! index 197
     '      KO2 + MCO3 --> ALD2 + MCO3 + MO2                                                              ', & ! index 198
     '     RIO2 + MCO3 --> CO2 + 0.113 DIBOO + 0.14 HC5 + 0.747 CH2O + 0.294 MACR + 0.453 MVK + MO2 + 0.88', & ! index 199
     '    HC5OO + MCO3 --> 0.29 DHMOB + 0.17 MOBA + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY + 0.216 HAC + MO2', & ! index 200
     '     VRO2 + MCO3 --> 0.6 GLYC + 0.4 MGLY + 0.4 CH2O + 0.6 MCO3 + MO2 + 0.4 HO2                      ', & ! index 201
     '     MRO2 + MCO3 --> 0.143 MGLY + 0.143 CH2O + 0.857 HAC + MO2 + 0.857 CO + 0.85 HO2                ', & ! index 202
     '     B3O2 + MCO3 --> ACET + MO2 + HO2                                                               ', & ! index 203
     '     R4N1 + MCO3 --> 0.39 CH2O + 0.3 R4O2 + 0.75 ALD2 + MO2 + 0.57 RCHO + NO2                       ', & ! index 204
     '     MAN2 + MCO3 --> CO2 + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + MO2 + 0.5 CO + 0.5 HO2 + 0.5 NO2      ', & ! index 205
     '     INO2 + MCO3 --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK + MO2 + 0.8 HO2 + 0.3 ', & ! index 206
     '     PRN1 + MCO3 --> CH2O + ALD2 + MO2 + NO2                                                        ', & ! index 207
     '     R4O2 + MCO3 --> ACTA + MEK                                                                     ', & ! index 208
     '     ATO2 + MCO3 --> ACTA + MEK                                                                     ', & ! index 209
     '      KO2 + MCO3 --> ACTA + MEK                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '     RIO2 + MCO3 --> ACTA + MEK                                                                     ', & ! index 211
     '    HC5OO + MCO3 --> ACTA + MEK                                                                     ', & ! index 212
     '     VRO2 + MCO3 --> ACTA + MEK                                                                     ', & ! index 213
     '     MRO2 + MCO3 --> ACTA + MEK                                                                     ', & ! index 214
     '     R4N1 + MCO3 --> ACTA + RCHO + NO2                                                              ', & ! index 215
     '     MAN2 + MCO3 --> ACTA + RCHO + NO2                                                              ', & ! index 216
     '     INO2 + MCO3 --> ACTA + RCHO + NO2                                                              ', & ! index 217
     '     PRN1 + MCO3 --> ACTA + RCHO + NO2                                                              ', & ! index 218
     '     B3O2 + MCO3 --> ACTA + ACET                                                                    ', & ! index 219
     '     ETO2 + MCO3 --> ALD2 + MO2 + HO2                                                               ', & ! index 220
     '     ETO2 + MCO3 --> ACTA + ALD2                                                                    ', & ! index 221
     '     RCO3 + MCO3 --> ETO2 + MO2                                                                     ', & ! index 222
     '     MAO3 + MCO3 --> CH2O + MCO3 + MO2                                                              ', & ! index 223
     '           2 NO3 --> 2 NO2 + O2                                                                     ', & ! index 224
     '       MO2 + NO2 --> MPN                                                                            ', & ! index 225
     '             MPN --> MO2 + NO2                                                                      ', & ! index 226
     '     ISOPNB + O3 --> 0.61 MVKN + 0.39 MACRN + CH2O + 0.27 OH                                        ', & ! index 227
     '     ISOPND + O3 --> 0.5 ETHLN + 0.5 PROPNN + 0.5 GLYC + 0.5 HAC + 0.27 OH                          ', & ! index 228
     '             HO2 --> O2                                                                             ', & ! index 229
     '             NO2 --> 0.5 HNO2 + 0.5 HNO3                                                            ', & ! index 230
     '             NO3 --> HNO3                                                                           ', & ! index 231
     '            N2O5 --> 2 HNO3                                                                         ', & ! index 232
     '        DMS + OH --> SO2 + CH2O + MO2                                                               ', & ! index 233
     '        DMS + OH --> 0.25 MSA + 0.75 SO2 + MO2                                                      ', & ! index 234
     '       DMS + NO3 --> HNO3 + SO2 + CH2O + MO2                                                        ', & ! index 235
     '        SO2 + OH --> SO4 + HO2                                                                      ', & ! index 236
     '         O3 + Br --> BrO + O2                                                                       ', & ! index 237
     '       BrO + HO2 --> HOBr + O2                                                                      ', & ! index 238
     '        HO2 + Br --> HBr + O2                                                                       ', & ! index 239
     '        HBr + OH --> Br + H2O                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '           2 BrO --> 2 Br + O2                                                                      ', & ! index 241
     '           2 BrO --> Br2 + O2                                                                       ', & ! index 242
     '        BrO + NO --> NO2 + Br                                                                       ', & ! index 243
     '      BrNO3 + Br --> Br2 + NO3                                                                      ', & ! index 244
     '        Br2 + OH --> HOBr + Br                                                                      ', & ! index 245
     '        BrO + OH --> HO2 + Br                                                                       ', & ! index 246
     '        NO3 + Br --> BrO + NO2                                                                      ', & ! index 247
     '       CH2O + Br --> HBr + CO + HO2                                                                 ', & ! index 248
     '       ALD2 + Br --> HBr + MCO3 + CO                                                                ', & ! index 249
     '       ACET + Br --> HBr + ATO2 + CO                                                                ', & ! index 250
     '       C2H6 + Br --> HBr + ETO2 + CO                                                                ', & ! index 251
     '       C3H8 + Br --> HBr + A3O2 + CO                                                                ', & ! index 252
     '        NO2 + Br --> BrNO2                                                                          ', & ! index 253
     '       BrO + NO2 --> BrNO3                                                                          ', & ! index 254
     '      CHBr3 + OH --> 3 Br                                                                           ', & ! index 255
     '     CH2Br2 + OH --> 2 Br                                                                           ', & ! index 256
     '      CH3Br + OH --> Br                                                                             ', & ! index 257
     '           BrNO3 --> HOBr + HNO3                                                                    ', & ! index 258
     '            HOBr --> 0.5 Br2 + H2O                                                                  ', & ! index 259
     '             HBr --> 0.5 Br2                                                                        ', & ! index 260
     '            HOBr --> 0.5 Br2 + H2O                                                                  ', & ! index 261
     '             HBr --> 0.5 Br2                                                                        ', & ! index 262
     '        HC5 + OH --> HC5OO                                                                          ', & ! index 263
     '      HC5OO + NO --> 0.29 DHMOB + 0.17 MOBA + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY + 0.216 HAC + 0.0', & ! index 264
     '      HC5OO + NO --> HNO3                                                                           ', & ! index 265
     '     HC5OO + HO2 --> 0.1 IAP + 0.9 GLYC + 0.9 MGLY + 0.9 OH + 0.9 HO2                               ', & ! index 266
     '     ISOPND + OH --> ISOPNDO2                                                                       ', & ! index 267
     '     ISOPNB + OH --> ISOPNBO2                                                                       ', & ! index 268
     '   ISOPNDO2 + NO --> 0.13 ETHLN + 0.31 HCOOH + 0.15 PROPNN + 0.07 MACRN + 0.15 GLYC + 0.65 CH2O + 0.', & ! index 269
     '   ISOPNDO2 + NO --> HNO3                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '  ISOPNDO2 + HO2 --> 0.065 ETHLN + 0.155 HCOOH + 0.5 ISNP + 0.075 PROPNN + 0.035 MACRN + 0.075 GLYC ', & ! index 271
     '   ISOPNBO2 + NO --> 0.14 MVKN + 0.26 MACRN + 0.6 GLYC + 0.4 CH2O + 0.6 HAC + 0.4 HO2 + 1.6 NO2     ', & ! index 272
     '   ISOPNBO2 + NO --> HNO3                                                                           ', & ! index 273
     '  ISOPNBO2 + HO2 --> 0.5 ISNP + 0.07 MVKN + 0.13 MACRN + 0.3 GLYC + 0.2 CH2O + 0.3 HAC + 0.5 OH + 0.', & ! index 274
     '       ISNP + OH --> 0.612 R4N1 + 0.193 ISOPNBO2 + 0.193 ISOPNDO2 + 0.612 OH                        ', & ! index 275
     '       MVKN + OH --> 0.35 PYAC + 0.65 HCOOH + 0.65 MGLY + 0.35 CH2O + NO3                           ', & ! index 276
     '      MACRN + OH --> MACRNO2                                                                        ', & ! index 277
     '    MACRNO2 + NO --> 0.93 CO2 + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.08 CH2O + 0.85 HAC + 0.15 NO3', & ! index 278
     '   MACRNO2 + HO2 --> 0.93 CO2 + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.08 CH2O + 0.85 HAC + OH + 0.1', & ! index 279
     '   MACRNO2 + NO2 --> PMNN                                                                           ', & ! index 280
     '            PMNN --> MACRNO2 + NO2                                                                  ', & ! index 281
     '      DHMOB + OH --> 0.5 HAC + 0.5 MEK + 1.5 CO + HO2                                               ', & ! index 282
     '      DIBOO + NO --> 0.48 GLYX + 0.52 GLYC + 0.52 MGLY + 0.48 HAC + HO2 + NO2                       ', & ! index 283
     '      DIBOO + NO --> HNO3                                                                           ', & ! index 284
     '     DIBOO + HO2 --> 0.85 R4P + 0.072 GLYX + 0.078 GLYC + 0.078 MGLY + 0.072 HAC + 0.15 OH + 0.15 HO', & ! index 285
     '       MOBA + OH --> MOBAOO                                                                         ', & ! index 286
     '     MOBAOO + NO --> CO2 + RCHO + HO2 + NO2                                                         ', & ! index 287
     '     MOBAOO + NO --> HNO3                                                                           ', & ! index 288
     '    MOBAOO + HO2 --> 0.5 CO2 + 0.5 R4P + 0.5 OH + 0.5 RCHO + 0.5 HO2                                ', & ! index 289
     '       MOBA + O3 --> CO2 + MEK + OH + HO2                                                           ', & ! index 290
     '      ETHLN + OH --> CO2 + CH2O + NO2                                                               ', & ! index 291
     '     PROPNN + OH --> MGLY + NO2                                                                     ', & ! index 292
     '      CH2OO + NO --> CH2O + NO2                                                                     ', & ! index 293
     '     CH2OO + NO2 --> CH2O + NO3                                                                     ', & ! index 294
     '     CH2OO + SO2 --> SO4 + CH2O                                                                     ', & ! index 295
     '     CH2OO + H2O --> H2O2 + CH2O                                                                    ', & ! index 296
     '     CH2OO + H2O --> HCOOH                                                                          ', & ! index 297
     '     MACROO + CO --> MACR                                                                           ', & ! index 298
     '     MACROO + NO --> MACR + NO2                                                                     ', & ! index 299
     '    MACROO + NO2 --> MACR + NO3                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '    MACROO + SO2 --> SO4 + MACR                                                                     ', & ! index 301
     '    MACROO + H2O --> MRP                                                                            ', & ! index 302
     '    MACROO + H2O --> H2O2 + MACR                                                                    ', & ! index 303
     '      MVKOO + CO --> MVK                                                                            ', & ! index 304
     '      MVKOO + NO --> MVK + NO2                                                                      ', & ! index 305
     '     MVKOO + NO2 --> MVK + NO3                                                                      ', & ! index 306
     '     MVKOO + SO2 --> SO4 + MVK                                                                      ', & ! index 307
     '     MVKOO + H2O --> H2O2 + MVK                                                                     ', & ! index 308
     '     MGLYOO + CO --> MGLY                                                                           ', & ! index 309
     '     MGLYOO + NO --> MGLY + NO2                                                                     ', & ! index 310
     '    MGLYOO + NO2 --> MGLY + NO3                                                                     ', & ! index 311
     '    MGLYOO + SO2 --> SO4 + MGLY                                                                     ', & ! index 312
     '    MGLYOO + H2O --> H2O2 + MGLY                                                                    ', & ! index 313
     '      MGLOO + CO --> MGLY                                                                           ', & ! index 314
     '      MGLOO + NO --> MGLY + NO2                                                                     ', & ! index 315
     '     MGLOO + NO2 --> MGLY + NO3                                                                     ', & ! index 316
     '     MGLOO + SO2 --> SO4 + MGLY                                                                     ', & ! index 317
     '     MGLOO + H2O --> MCO3 + MO2                                                                     ', & ! index 318
     '     MGLOO + H2O --> H2O2 + MGLY                                                                    ', & ! index 319
     '    CH3CHOO + CO --> ALD2                                                                           ', & ! index 320
     '    CH3CHOO + NO --> ALD2 + NO2                                                                     ', & ! index 321
     '   CH3CHOO + NO2 --> ALD2 + NO3                                                                     ', & ! index 322
     '   CH3CHOO + SO2 --> SO4 + ALD2                                                                     ', & ! index 323
     '   CH3CHOO + H2O --> H2O2 + ALD2                                                                    ', & ! index 324
     '   CH3CHOO + H2O --> ACTA                                                                           ', & ! index 325
     '       GAOO + CO --> GLYC                                                                           ', & ! index 326
     '       GAOO + NO --> GLYC + NO2                                                                     ', & ! index 327
     '      GAOO + NO2 --> GLYC + NO3                                                                     ', & ! index 328
     '      GAOO + SO2 --> SO4 + GLYC                                                                     ', & ! index 329
     '      GAOO + H2O --> H2O2 + GLYC                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '      GAOO + H2O --> HAC                                                                            ', & ! index 331
     '       BENZ + OH --> BRO2                                                                           ', & ! index 332
     '       TOLU + OH --> TRO2                                                                           ', & ! index 333
     '       XYLE + OH --> XRO2                                                                           ', & ! index 334
     '            MONX --> 3 CH2O                                                                         ', & ! index 335
     '      BRO2 + HO2 --> LBRO2H                                                                         ', & ! index 336
     '       BRO2 + NO --> LBRO2N                                                                         ', & ! index 337
     '      TRO2 + HO2 --> LTRO2H                                                                         ', & ! index 338
     '       TRO2 + NO --> LTRO2N                                                                         ', & ! index 339
     '      XRO2 + HO2 --> LXRO2H                                                                         ', & ! index 340
     '       XRO2 + NO --> LXRO2N                                                                         ', & ! index 341
     '              O3 --> 2 OH                                                                           ', & ! index 342
     '              O3 --> OH + HO2                                                                       ', & ! index 343
     '             NO2 --> O3 + NO                                                                        ', & ! index 344
     '            H2O2 --> 2 OH                                                                           ', & ! index 345
     '              MP --> CH2O + OH + HO2                                                                ', & ! index 346
     '            CH2O --> CO + 2 HO2                                                                     ', & ! index 347
     '            CH2O --> CO + H2                                                                        ', & ! index 348
     '            HNO3 --> OH + NO2                                                                       ', & ! index 349
     '            HNO2 --> OH + NO                                                                        ', & ! index 350
     '            HNO4 --> OH + NO3                                                                       ', & ! index 351
     '            HNO4 --> HO2 + NO2                                                                      ', & ! index 352
     '             NO3 --> O3 + NO2                                                                       ', & ! index 353
     '             NO3 --> NO + O2                                                                        ', & ! index 354
     '            N2O5 --> NO3 + NO2                                                                      ', & ! index 355
     '            ALD2 --> 0.12 MCO3 + 0.88 MO2 + 0.88 CO + HO2                                           ', & ! index 356
     '            ALD2 --> CO + CH4                                                                       ', & ! index 357
     '             PAN --> 0.7 MCO3 + 0.3 MO2 + 0.3 NO3 + 0.7 NO2                                         ', & ! index 358
     '            RCHO --> ETO2 + CO + HO2                                                                ', & ! index 359
     '            ACET --> MCO3 + MO2                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '            ACET --> 2 MO2 + CO                                                                     ', & ! index 361
     '             MEK --> 0.85 ETO2 + 0.15 RCO3 + 0.85 MCO3 + 0.15 MO2                                   ', & ! index 362
     '            GLYC --> 0.9 CH2O + 0.07 OH + CO + 1.73 HO2 + 0.1 MOH                                   ', & ! index 363
     '            GLYX --> 2 CO + 2 HO2                                                                   ', & ! index 364
     '            GLYX --> 2 CO + H2                                                                      ', & ! index 365
     '            GLYX --> CH2O + CO                                                                      ', & ! index 366
     '            MGLY --> MCO3 + CO + HO2                                                                ', & ! index 367
     '             MVK --> PRPE + CO                                                                      ', & ! index 368
     '             MVK --> CH2O + MCO3 + CO + HO2                                                         ', & ! index 369
     '             MVK --> RCO3 + MO2                                                                     ', & ! index 370
     '            MACR --> CH2O + MCO3 + CO + HO2                                                         ', & ! index 371
     '             HAC --> CH2O + MCO3 + HO2                                                              ', & ! index 372
     '            INPN --> OH + RCHO + HO2 + NO2                                                          ', & ! index 373
     '            PRPN --> OH + RCHO + HO2 + NO2                                                          ', & ! index 374
     '             ETP --> ALD2 + OH + HO2                                                                ', & ! index 375
     '            RA3P --> OH + RCHO + HO2                                                                ', & ! index 376
     '            RB3P --> ACET + OH + HO2                                                                ', & ! index 377
     '             R4P --> OH + RCHO + HO2                                                                ', & ! index 378
     '              PP --> CH2O + ALD2 + OH + HO2                                                         ', & ! index 379
     '              RP --> ALD2 + OH + HO2                                                                ', & ! index 380
     '             RIP --> 0.29 HC5 + 0.71 CH2O + 0.285 MACR + 0.425 MVK + OH + HO2                       ', & ! index 381
     '             IAP --> 0.26 GLYC + 0.58 MGLY + 0.36 HAC + OH + 0.67 CO + HO2 + 0.19 H2                ', & ! index 382
     '            ISNP --> OH + RCHO + HO2 + NO2                                                          ', & ! index 383
     '             VRP --> 0.7 GLYC + 0.3 MGLY + 0.3 CH2O + 0.7 MCO3 + OH + 0.3 HO2                       ', & ! index 384
     '             MRP --> 0.5 CH2O + HAC + OH + 0.5 CO + HO2                                             ', & ! index 385
     '            MAOP --> CH2O + MCO3 + OH                                                               ', & ! index 386
     '            R4N2 --> 0.32 ACET + 0.05 A3O2 + 0.18 B3O2 + 0.32 ETO2 + 0.32 ALD2 + 0.19 MEK + 0.18 MO2', & ! index 387
     '             MAP --> OH + MO2                                                                       ', & ! index 388
     '           MACRN --> MGLY + 0.5 CH2O + HAC + 0.5 CO + HO2 + NO2                                     ', & ! index 389
     '            MVKN --> GLYC + MCO3 + NO2                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '          ISOPNB --> HC5 + HO2 + NO2                                                                ', & ! index 391
     '             Br2 --> 2 Br                                                                           ', & ! index 392
     '             BrO --> O3 + Br                                                                        ', & ! index 393
     '            HOBr --> OH + Br                                                                        ', & ! index 394
     '           BrNO3 --> NO3 + Br                                                                       ', & ! index 395
     '           BrNO3 --> BrO + NO2                                                                      ', & ! index 396
     '           BrNO2 --> NO2 + Br                                                                       ', & ! index 397
     '           CHBr3 --> 3 Br                                                                           ', & ! index 398
     '             MPN --> CH2O + NO3 + HO2                                                               ', & ! index 399
     '             MPN --> MO2 + NO2                                                                      ', & ! index 400
     '          ISOPND --> HC5 + HO2 + NO2                                                                ', & ! index 401
     '          PROPNN --> CH2O + MO2 + CO + NO2                                                          ', & ! index 402
     '           ATOOH --> CH2O + MCO3 + OH                                                               ', & ! index 403
     '        ACE + OH --> RX1 + PRX1 + OH                                                                ', & ! index 404
     '        ACY + OH --> RX2 + PRX2 + OH                                                                ', & ! index 405
     '        ANT + OH --> RX3 + PRX3 + OH                                                                ', & ! index 406
     '        BAA + OH --> RX4 + PRX4 + OH                                                                ', & ! index 407
     '        BAP + OH --> RX5 + PRX5 + OH                                                                ', & ! index 408
     '        BBF + OH --> RX6 + PRX6 + OH                                                                ', & ! index 409
     '        BHP + OH --> RX7 + PRX7 + OH                                                                ', & ! index 410
     '        BKF + OH --> RX8 + PRX8 + OH                                                                ', & ! index 411
     '        CHR + OH --> RX9 + PRX9 + OH                                                                ', & ! index 412
     '       DAHA + OH --> RX10 + PRX10 + OH                                                              ', & ! index 413
     '        FLA + OH --> RX11 + PRX11 + OH                                                              ', & ! index 414
     '        FLO + OH --> RX12 + PRX12 + OH                                                              ', & ! index 415
     '       ICDP + OH --> RX13 + PRX13 + OH                                                              ', & ! index 416
     '        NAP + OH --> RX14 + PRX14 + NAPAD                                                           ', & ! index 417
     '     NAPAD + NO2 --> NNAP + RX15 + PRX15                                                            ', & ! index 418
     '      NAPAD + O2 --> RX16 + PRX16 + O2                                                              ', & ! index 419
     '        PHE + OH --> RX17 + PRX17 + OH                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '        PYR + OH --> RX18 + PRX18 + PYRAD + OH                                                      ', & ! index 421
     '      PYRAD + O2 --> RX19 + PRX19 + O2                                                              ', & ! index 422
     '     PYRAD + NO2 --> RX20 + PRX20 + 0.2 BAPB + 0.2 BAPBBCPI + 0.2 BAPBBCPO + 0.2 BAPBOCPI + 0.2 BAPB', & ! index 423
     ' PYR + NO3 + NO2 --> RX21 + PRX21 + 0.2 BAPB + 0.2 BAPBBCPI + 0.2 BAPBBCPO + 0.2 BAPBOCPI + 0.2 BAPB', & ! index 424
     '       BAPB + OH --> RX22 + PRX22 + BAPBAD                                                          ', & ! index 425
     '     BAPBAD + O2 --> RX23 + PRX23 + O2                                                              ', & ! index 426
     '    BAPBAD + NO2 --> RX24 + PRX24 + 0.2 BAPC + 0.2 BAPCBCPI + 0.2 BAPCBCPO + 0.2 BAPCOCPI + 0.2 BAPC', & ! index 427
     'BAPB + NO3 + NO2 --> RX25 + PRX25 + 0.2 BAPC + 0.2 BAPCBCPI + 0.2 BAPCBCPO + 0.2 BAPCOCPI + 0.2 BAPC', & ! index 428
     '       BAPC + OH --> RX26 + PRX26 + OH                                                              ', & ! index 429
     'BAPC + NO3 + NO2 --> RX27 + PRX27 + OH                                                              ', & ! index 430
     '    ACEBCPO + O3 --> RX75 + PRX75 + OH                                                              ', & ! index 431
     '    ACEBCPI + O3 --> RX76 + PRX76 + OH                                                              ', & ! index 432
     '    ACEOCPO + O3 --> RX77 + PRX77 + OH                                                              ', & ! index 433
     '    ACEOCPI + O3 --> RX78 + PRX78 + OH                                                              ', & ! index 434
     '    ACYBCPO + O3 --> RX79 + PRX79 + OH                                                              ', & ! index 435
     '    ACYBCPI + O3 --> RX80 + PRX80 + OH                                                              ', & ! index 436
     '    ACYOCPO + O3 --> RX81 + PRX81 + OH                                                              ', & ! index 437
     '    ACYOCPI + O3 --> RX82 + PRX82 + OH                                                              ', & ! index 438
     '    ANTBCPO + O3 --> RX83 + PRX83 + OH                                                              ', & ! index 439
     '    ANTBCPI + O3 --> RX84 + PRX84 + OH                                                              ', & ! index 440
     '    ANTOCPO + O3 --> RX85 + PRX85 + OH                                                              ', & ! index 441
     '    ANTOCPI + O3 --> RX86 + PRX86 + OH                                                              ', & ! index 442
     '    BAABCPO + O3 --> RX87 + PRX87 + OH                                                              ', & ! index 443
     '    BAABCPI + O3 --> RX88 + PRX88 + OH                                                              ', & ! index 444
     '    BAAOCPO + O3 --> RX89 + PRX89 + OH                                                              ', & ! index 445
     '    BAAOCPI + O3 --> RX90 + PRX90 + OH                                                              ', & ! index 446
     '    BAPBCPO + O3 --> RX91 + PRX91 + OH                                                              ', & ! index 447
     '    BAPBCPI + O3 --> RX92 + PRX92 + OH                                                              ', & ! index 448
     '    BAPOCPO + O3 --> RX93 + PRX93 + OH                                                              ', & ! index 449
     '    BAPOCPI + O3 --> RX94 + PRX94 + OH                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '    BBFBCPO + O3 --> RX95 + PRX95 + OH                                                              ', & ! index 451
     '    BBFBCPI + O3 --> RX96 + PRX96 + OH                                                              ', & ! index 452
     '    BBFOCPO + O3 --> RX97 + PRX97 + OH                                                              ', & ! index 453
     '    BBFOCPI + O3 --> RX98 + PRX98 + OH                                                              ', & ! index 454
     '    BHPBCPO + O3 --> RX99 + PRX99 + OH                                                              ', & ! index 455
     '    BHPBCPI + O3 --> RX100 + PRX100 + PRX110 + OH                                                   ', & ! index 456
     '    BHPOCPO + O3 --> RX101 + PRX101 + OH                                                            ', & ! index 457
     '    BHPOCPI + O3 --> RX102 + PRX102 + OH                                                            ', & ! index 458
     '    BKFBCPO + O3 --> RX103 + PRX103 + OH                                                            ', & ! index 459
     '    BKFBCPI + O3 --> RX104 + PRX104 + OH                                                            ', & ! index 460
     '    BKFOCPO + O3 --> RX105 + PRX105 + OH                                                            ', & ! index 461
     '    BKFOCPI + O3 --> RX106 + PRX106 + OH                                                            ', & ! index 462
     '    CHRBCPO + O3 --> RX107 + PRX107 + OH                                                            ', & ! index 463
     '    CHRBCPI + O3 --> RX108 + PRX108 + OH                                                            ', & ! index 464
     '    CHROCPO + O3 --> RX109 + PRX109 + OH                                                            ', & ! index 465
     '    CHROCPI + O3 --> RX110 + OH                                                                     ', & ! index 466
     '   DAHABCPO + O3 --> RX111 + PRX111 + OH                                                            ', & ! index 467
     '   DAHABCPI + O3 --> RX112 + PRX112 + OH                                                            ', & ! index 468
     '   DAHAOCPO + O3 --> RX113 + PRX113 + OH                                                            ', & ! index 469
     '   DAHAOCPI + O3 --> RX114 + PRX114 + OH                                                            ', & ! index 470
     '    FLABCPO + O3 --> RX115 + PRX115 + OH                                                            ', & ! index 471
     '    FLABCPI + O3 --> RX60 + PRX60 + OH                                                              ', & ! index 472
     '    FLAOCPO + O3 --> RX61 + PRX61 + OH                                                              ', & ! index 473
     '    FLAOCPI + O3 --> RX62 + PRX62 + OH                                                              ', & ! index 474
     '    FLOBCPO + O3 --> RX63 + PRX63 + OH                                                              ', & ! index 475
     '    FLOBCPI + O3 --> RX64 + PRX64 + OH                                                              ', & ! index 476
     '    FLOOCPO + O3 --> RX65 + PRX65 + OH                                                              ', & ! index 477
     '    FLOOCPI + O3 --> RX66 + PRX66 + OH                                                              ', & ! index 478
     '   ICDPBCPO + O3 --> RX67 + PRX67 + OH                                                              ', & ! index 479
     '   ICDPBCPI + O3 --> RX68 + PRX68 + OH                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '   ICDPOCPO + O3 --> RX69 + PRX69 + OH                                                              ', & ! index 481
     '   ICDPOCPI + O3 --> RX70 + PRX70 + OH                                                              ', & ! index 482
     '    PHEBCPO + O3 --> RX71 + PRX71 + OH                                                              ', & ! index 483
     '    PHEBCPI + O3 --> RX72 + PRX72 + OH                                                              ', & ! index 484
     '    PHEOCPO + O3 --> RX73 + PRX73 + OH                                                              ', & ! index 485
     '    PHEOCPI + O3 --> RX74 + PRX74 + OH                                                              ', & ! index 486
     '    PYRBCPO + O3 --> RX28 + PRX28 + OH                                                              ', & ! index 487
     '    PYRBCPI + O3 --> RX29 + PRX29 + OH                                                              ', & ! index 488
     '    PYROCPO + O3 --> RX30 + PRX30 + OH                                                              ', & ! index 489
     '    PYROCPI + O3 --> RX31 + PRX31 + OH                                                              ', & ! index 490
     '   BAPBBCPO + O3 --> RX32 + PRX32 + OH                                                              ', & ! index 491
     '   BAPBBCPI + O3 --> RX33 + PRX33 + OH                                                              ', & ! index 492
     '   BAPBOCPO + O3 --> RX34 + PRX34 + OH                                                              ', & ! index 493
     '   BAPBOCPI + O3 --> RX35 + PRX35 + OH                                                              ', & ! index 494
     '   BAPCBCPO + O3 --> RX36 + PRX36 + OH                                                              ', & ! index 495
     '   BAPCBCPI + O3 --> RX37 + PRX37 + OH                                                              ', & ! index 496
     '   BAPCOCPO + O3 --> RX38 + PRX38 + OH                                                              ', & ! index 497
     '   BAPCOCPI + O3 --> RX39 + PRX39 + OH                                                              ', & ! index 498
     '   PYRBCPO + NO3 --> RX40 + PRX40 + 0.2 BAPB + 0.2 BAPBBCPI + 0.2 BAPBBCPO + 0.2 BAPBOCPI + 0.2 BAPB', & ! index 499
     '   PYRBCPI + NO3 --> RX41 + PRX41 + 0.2 BAPB + 0.2 BAPBBCPI + 0.2 BAPBBCPO + 0.2 BAPBOCPI + 0.2 BAPB', & ! index 500
     '   PYROCPO + NO3 --> RX42 + PRX42 + 0.2 BAPB + 0.2 BAPBBCPI + 0.2 BAPBBCPO + 0.2 BAPBOCPI + 0.2 BAPB', & ! index 501
     '   PYROCPI + NO3 --> RX43 + PRX43 + 0.2 BAPB + 0.2 BAPBBCPI + 0.2 BAPBBCPO + 0.2 BAPBOCPI + 0.2 BAPB', & ! index 502
     '  BAPBBCPO + NO3 --> RX44 + PRX44 + 0.2 BAPC + 0.2 BAPCBCPI + 0.2 BAPCBCPO + 0.2 BAPCOCPI + 0.2 BAPC', & ! index 503
     '  BAPBBCPI + NO3 --> RX45 + PRX45 + 0.2 BAPC + 0.2 BAPCBCPI + 0.2 BAPCBCPO + 0.2 BAPCOCPI + 0.2 BAPC', & ! index 504
     '  BAPBOCPO + NO3 --> RX46 + PRX46 + 0.2 BAPC + 0.2 BAPCBCPI + 0.2 BAPCBCPO + 0.2 BAPCOCPI + 0.2 BAPC', & ! index 505
     '  BAPBOCPI + NO3 --> RX47 + PRX47 + 0.2 BAPC + 0.2 BAPCBCPI + 0.2 BAPCBCPO + 0.2 BAPCOCPI + 0.2 BAPC', & ! index 506
     '  BAPCBCPO + NO3 --> RX48 + PRX48 + OH                                                              ', & ! index 507
     '  BAPCBCPI + NO3 --> RX49 + PRX49 + OH                                                              ', & ! index 508
     '  BAPCOCPO + NO3 --> RX50 + PRX50 + OH                                                              ', & ! index 509
     '  BAPCOCPI + NO3 --> RX51 + PRX51 + OH                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(9) :: EQN_NAMES_17 = (/ &
     '            NNAP --> O2                                                                             ', & ! index 511
     '        BAPCBCPI --> RX52 + PRX52 + O2                                                              ', & ! index 512
     '        BAPCBCPO --> RX53 + PRX53 + O2                                                              ', & ! index 513
     '        BAPCOCPI --> RX54 + PRX54 + O2                                                              ', & ! index 514
     '        BAPCOCPO --> RX55 + PRX55 + O2                                                              ', & ! index 515
     '        BAPBBCPI --> RX56 + PRX56 + O2                                                              ', & ! index 516
     '        BAPBBCPO --> RX57 + PRX57 + O2                                                              ', & ! index 517
     '        BAPBOCPI --> RX58 + PRX58 + O2                                                              ', & ! index 518
     '        BAPBOCPO --> RX59 + PRX59 + O2                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(519) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: FAM_NAMES_0 = (/ &
     'PRX1           ','PRX2           ','PRX3           ', & ! index 1 - 3
     'PRX4           ','PRX5           ','PRX6           ', & ! index 4 - 6
     'PRX7           ','PRX8           ','PRX9           ', & ! index 7 - 9
     'PRX10          ','PRX11          ','PRX12          ', & ! index 10 - 12
     'PRX13          ','PRX14          ','PRX15          ', & ! index 13 - 15
     'PRX16          ','PRX17          ','PRX18          ', & ! index 16 - 18
     'PRX19          ','PRX20          ','PRX21          ', & ! index 19 - 21
     'PRX22          ','PRX23          ','PRX24          ', & ! index 22 - 24
     'PRX25          ','PRX26          ','PRX27          ', & ! index 25 - 27
     'PRX28          ','PRX29          ','PRX30          ', & ! index 28 - 30
     'PRX31          ','PRX32          ','PRX33          ', & ! index 31 - 33
     'PRX34          ','PRX35          ','PRX36          ', & ! index 34 - 36
     'PRX37          ','PRX38          ','PRX39          ', & ! index 37 - 39
     'PRX40          ','PRX41          ','PRX42          ', & ! index 40 - 42
     'PRX43          ','PRX44          ','PRX45          ', & ! index 43 - 45
     'PRX46          ','PRX47          ','PRX48          ', & ! index 46 - 48
     'PRX49          ','PRX50          ','PRX51          ', & ! index 49 - 51
     'PRX52          ','PRX53          ','PRX54          ', & ! index 52 - 54
     'PRX55          ','PRX56          ','PRX57          ', & ! index 55 - 57
     'PRX58          ','PRX59          ','PRX60          ', & ! index 58 - 60
     'PRX61          ','PRX62          ','PRX63          ', & ! index 61 - 63
     'PRX64          ','PRX65          ','PRX66          ', & ! index 64 - 66
     'PRX67          ','PRX68          ','PRX69          ', & ! index 67 - 69
     'PRX70          ','PRX71          ','PRX72          ', & ! index 70 - 72
     'PRX73          ','PRX74          ','PRX75          ', & ! index 73 - 75
     'PRX76          ','PRX77          ','PRX78          ', & ! index 76 - 78
     'PRX79          ','PRX80          ','PRX81          ', & ! index 79 - 81
     'PRX82          ','PRX83          ','PRX84          ', & ! index 82 - 84
     'PRX85          ','PRX86          ','PRX87          ', & ! index 85 - 87
     'PRX88          ','PRX89          ','PRX90          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(25) :: FAM_NAMES_1 = (/ &
     'PRX91          ','PRX92          ','PRX93          ', & ! index 91 - 93
     'PRX94          ','PRX95          ','PRX96          ', & ! index 94 - 96
     'PRX97          ','PRX98          ','PRX99          ', & ! index 97 - 99
     'PRX100         ','PRX101         ','PRX102         ', & ! index 100 - 102
     'PRX103         ','PRX104         ','PRX105         ', & ! index 103 - 105
     'PRX106         ','PRX107         ','PRX108         ', & ! index 106 - 108
     'PRX109         ','PRX110         ','PRX111         ', & ! index 109 - 111
     'PRX112         ','PRX113         ','PRX114         ', & ! index 112 - 114
     'PRX115         ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(115) :: FAM_NAMES = (/&
    FAM_NAMES_0, FAM_NAMES_1 /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
